version: '3.1'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: medpharm_mysql
    environment:
      MYSQL_DATABASE: Medpharm
      MYSQL_ROOT_PASSWORD: meet123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  medpharm.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medpharm_api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:80"
